name: CI

on:
workflow_dispatch:
schedule:
- cron: "*/5 * * * *"

jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3

```
  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 16

  - name: Install dependencies
    run: npm ci

  - name: Run Upptime
    run: npm run ci

  - name: Commit and push if changes
    run: |
      git config user.name "Upptime Bot"
      git config user.email "73812536+upptime-bot@users.noreply.github.com"
      git add .
      git commit -m "Update [skip ci]" || exit 0
      git push
```
